import asyncio
import os
import subprocess
import sys

from flask import Flask, jsonify, render_template, request, send_from_directory
from dotenv import load_dotenv
from google import genai
from graphon_client import GraphonClient
from PIL import Image, ImageDraw, ImageFont

from figma_client import FigmaClient

# Load environment variables
load_dotenv()

app = Flask(__name__)

GEMINI_KEY = os.getenv("GEMINI_KEY")
GRAPHON_KEY = os.getenv("GRAPHON_KEY")

gemini_client = genai.Client(api_key=GEMINI_KEY)
graphon_client = GraphonClient(api_key=GRAPHON_KEY)
figma_bot = FigmaClient()

# Mutable state
GRAPH_GROUP_ID = None
AUDIT_LOGS = []


# --- IMAGE GENERATOR (NanoBanana Style) ---
def generate_nano_report(text: str) -> str:
    """Generates a visual 'Crisis Report' image."""
    img = Image.new("RGB", (800, 400), color=(20, 20, 20))
    draw = ImageDraw.Draw(img)
    draw.rectangle([(10, 10), (790, 390)], outline="#ff4444", width=5)
    draw.text((30, 30), "PROJECT 12 :: AUDIT REPORT", fill="#ff4444")
    draw.line([(30, 50), (770, 50)], fill="#ff4444", width=2)
    draw.text((30, 80), "CONFLICT DETECTED:", fill="white")

    margin = 30
    offset = 110
    words = text.split()
    line = ""
    for word in words:
        if len(line + word) < 40:
            line += word + " "
        else:
            draw.text((margin, offset), f"> {line}", fill="#00ff00")
            offset += 25
            line = word + " "
    draw.text((margin, offset), f"> {line}", fill="#00ff00")

    draw.text((30, 350), "GENERATED BY GEMINI 3 + GRAPHON", fill="#888")

    os.makedirs("assets", exist_ok=True)
    filename = "assets/generated_report.png"
    img.save(filename)
    return filename


def open_file_locally(filepath: str) -> None:
    """Opens a file using the OS default handler."""
    abs_path = os.path.abspath(filepath)
    if sys.platform == "win32":
        os.startfile(abs_path)
    elif sys.platform == "darwin":
        subprocess.call(["open", abs_path])
    else:
        subprocess.call(["xdg-open", abs_path])


@app.before_request
def setup():
    """Ingests the mock assets into GraphOn once at startup."""
    global GRAPH_GROUP_ID
    try:
        if not GRAPH_GROUP_ID:
            GRAPH_GROUP_ID = asyncio.run(
                graphon_client.upload_process_and_create_group(
                    file_paths=[
                        "assets/slide_revenue.png",
                        "assets/meeting_audio.mp3",
                    ],
                    group_name="Silent_Exec_Dashboard_Final",
                )
            )
            print(f"Graph ready! ID: {GRAPH_GROUP_ID}")
    except Exception as exc:  # noqa: BLE001
        print(f"Graph setup skipped: {exc}")


@app.route("/")
def index():
    return render_template("index.html")


@app.route("/assets/<path:filename>")
def serve_assets(filename):
    return send_from_directory("assets", filename)


@app.route("/api/command", methods=["POST"])
def handle_command():
    data = request.json or {}
    command = data.get("command")
    response = {"alert": "DONE", "color": "white"}

    if command == "AUDIT":
        audit = asyncio.run(
            graphon_client.query_group(
                GRAPH_GROUP_ID,
                "Compare revenue in slides vs audio.",
                return_source_data=True,
            )
        )
        gen = gemini_client.models.generate_content(
            model="gemini-2.0-flash-exp",
            contents=f"Summarize discrepancy (Max 10 words): {audit.answer}",
        )
        msg = gen.text.strip().upper()

        report_path = generate_nano_report(msg)
        open_file_locally(os.path.abspath(report_path))

        AUDIT_LOGS.append({"type": "RISK", "msg": msg})
        response["alert"] = "REPORT GENERATED"
        response["color"] = "#ff4444"

    elif command == "EXPORT":
        figma_path = figma_bot.create_design_ticket(AUDIT_LOGS)
        figma_bot.open_in_figma(figma_path)
        response["alert"] = "SYNCED TO FIGMA"
        response["color"] = "#A259FF"

    elif command == "APPROVE":
        AUDIT_LOGS.append({"type": "OK", "msg": "Section Verified"})
        response["alert"] = "VERIFIED"
        response["color"] = "#00C851"

    return jsonify(response)


if __name__ == "__main__":
    app.run(debug=True, port=5000)
