import matplotlib.pyplot as plt
import numpy as np

# 1. SETUP: Dark Mode / Cyberpunk Aesthetic
plt.style.use('dark_background')
fig, ax = plt.subplots(figsize=(10, 6))
fig.patch.set_facecolor('#0d0d0d') # Matches your dark UI
ax.set_facecolor('#0d0d0d')

# 2. DATA: "Q3 Financials" (The Mock Data)
categories = ['JUL', 'AUG', 'SEP', 'Q3 TOTAL']
values = [2.4, 3.1, 4.5, 10.0]

# 3. PLOT: Neon Green Bars
bars = ax.bar(categories, values, color='#00ff41', alpha=0.8, width=0.5)

# 4. STYLING: Make it look like a Figma Mockup
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.spines['left'].set_color('#333333')
ax.spines['bottom'].set_color('#333333')
ax.tick_params(axis='x', colors='#00ff41', labelsize=12)
ax.tick_params(axis='y', colors='#888888')
ax.grid(axis='y', linestyle='--', alpha=0.2, color='#00ff41')

# Add "AI Generated" Metadata annotations to sell the story
ax.set_title("ACME CORP :: Q3 REVENUE GROWTH (UNAUDITED)", 
             fontsize=14, color='white', pad=20, loc='left', fontname='monospace')
plt.text(2.5, 9.5, 'GENERATED BY: NANO-BANANA', 
         fontsize=10, color='#00ff41', alpha=0.6, fontname='monospace')

# 5. EXPORT: Save as the prop image
plt.tight_layout()
plt.savefig('demo_asset.png', dpi=100, facecolor='#0d0d0d')
print(">> ASSET GENERATED: demo_asset.png")
